# Screen dimensions
WORK_WIDTH = 180
WORK_HEIGHT = 280

RENDER_WIDTH = WORK_WIDTH * 5
RENDER_HEIGHT = WORK_HEIGHT * 5

# Image Paths
IMG_PATH_E = 'C:/Users/PC/Desktop/Projekty informatyka/Projekt DIY plotter/DIY-plotter/res/elon.png'
IMG_PATH_L = 'C:/Users/PC/Desktop/Projekty informatyka/Projekt DIY plotter/DIY-plotter/res/lena.png'

# Offsets
LINE_SPACING = 5
LINE_NUMBER = WORK_HEIGHT / LINE_SPACING
Y_OFFSET = 20
X_OFFSET = 20

# Sinus 
SINUS_MAX_AMPLITUDE = 5
SINUS_FREQUENCY = 0.5

# Image processing 
CONTRAST_FACTOR = 2.0

# Mechanical parts
GEARWHEEL = 20
GT2_TIMING_BELT_MM_TEETH = 2 

# Stepper motor 
STEPS_PER_NORMAL_RESOLUTION = 200
MICROSTEPPING = 16
STEPS_PER_MOD_RESOLUTION = STEPS_PER_NORMAL_RESOLUTION * MICROSTEPPING
STEPS_PER_MM = STEPS_PER_MOD_RESOLUTION / (GEARWHEEL * GT2_TIMING_BELT_MM_TEETH)
MECHANICAL_RESOLUTION_MM = 1 / STEPS_PER_MM # miara 1 kroku

# Arduino work space
X_AXIS_STEPS = STEPS_PER_MM * WORK_WIDTH
Y_AXIS_STEPS = STEPS_PER_MM * WORK_HEIGHT